data: !!str "data-basecos_exp-ring_graph-V16-mu0.100-alpha1.500-beta2.000-freq0.200-nt1-nl3-n1000"
T0: !!int 0
T1: !!int 50
tau_max: !!int 5 
mu: !!float 0.1 
n_basis_time: !!int 1 
n_basis_loc: !!int 3 

use_seq: !!int 500
loss: !!str "cont_l2_loss"
lr: !!float 0.1 
epoch: !!int 1000
batch_size: !!int 64
device: !!str "cpu"
seed: !!int 100

lam_reg: !!float 1e2

t_init: !!float 1e-3
t_upp: !!float 1e1
t_mul: !!float 1.3
b_bar: !!float 0.0125
b_upp: !!float -0.0125

penalty: !!bool True
reg: !!bool True
mae_eval: !!bool False
warm_start: !!bool False