data: !!str "fire_data"
T0: !!int 0
T1: !!int 365
tau_max: !!int 30 
mu: !!float 0.01
n_basis_time: !!int 1 
n_basis_loc: !!int 3

use_seq: !!int 5
loss: !!str "likelihood"
lr: !!float 0.1
epoch: !!int 1000
batch_size: !!int 32
device: !!str "cpu"
seed: !!int 100

lam_reg: !!float 1e4

t_init: !!float 1e-4
t_upp: !!float 1e0
t_mul: !!float 1.3
b_bar: !!float 0.00125
b_upp: !!float -0.00125

penalty: !!bool True
reg: !!bool True
mae_eval: !!bool False
warm_start: !!bool False