data: !!str "traffic_data"
T0: !!int 0
T1: !!int 18
tau_max: !!int 5
mu: !!float 0.02
n_basis_time: !!int 1 
n_basis_loc: !!int 2

use_seq: !!int 159
loss: !!str "likelihood"
lr: !!float 0.1
epoch: !!int 1000
batch_size: !!int 64
device: !!str "cpu"
seed: !!int 100

lam_reg: !!float 1e6

t_init: !!float 1e-3
t_upp: !!float 1e1
t_mul: !!float 1.3
b_bar: !!float 0.0025
b_upp: !!float -0.0025

penalty: !!bool True
reg: !!bool True
mae_eval: !!bool False
warm_start: !!bool False